winMessages:
  - "Glückwunsch, du hast gewonnen!"
  - "Das war dein Glückstag!"
  - "Jackpot! Du bist der Gewinner!"
  - "Du hast den Hauptpreis abgestaubt!"
  - "Nice! Dein Einsatz hat sich gelohnt!"
  - "Gewonnen! So geht das!"
  - "Bingo! Preis gehört dir!"
  - "Du bist der Champ!"
  - "Mega Glück, du hast abgesahnt!"
  - "Gewinn! Herzlichen Glückwunsch!"
  - "Der Sieg gehört dir!"
  - "Kasse klingelt: Du hast gewonnen!"
  - "Glückspilz! Der Preis ist dein!"
  - "Alles richtig gemacht, Glückwunsch!"
  - "Einsatz verdoppelt! Gewonnen!"
  - "Das war stark! Sieg für dich!"
  - "Du hast es geschafft! Preis für dich!"
  - "Du hast abgeräumt, Glückwunsch!"
  - "Gewinner! Dein Name steht oben!"
  - "Dein Glücksmoment ist da: Sieg!"

loseMessages:
  - "Leider verloren, versuch's nochmal!"
  - "Das war knapp, nächstes Mal!"
  - "Pech gehabt, Kopf hoch!"
  - "Heute nicht dein Tag, weiter so!"
  - "Leider nichts, vielleicht beim nächsten Mal!"
  - "Knapp daneben ist auch vorbei!"
  - "Das Glück war nicht auf deiner Seite."
  - "Keine Sorge, du hast es fast geschafft!"
  - "Leider verloren, gib nicht auf!"
  - "Es hat nicht gereicht, probier’s nochmal!"
  - "Schade, nächster Versuch!"
  - "Heute kein Glück, bleib dran!"
  - "Leider kein Gewinn, weiter geht's!"
  - "Pech gehabt, das war’s für heute!"
  - "Knapp verloren, bleib dran!"
  - "Das war nix, nächstes Mal klappt’s!"
  - "Kein Glück diesmal, Versuch zählt!"
  - "Leider nicht dein Tag, probier’s wieder!"
  - "Du warst nah dran, gib nicht auf!"
  - "Verloren, aber das nächste Mal gehörst du dazu!"
